plugins:
  - jekyll-feed

url: https://thefollow.io/follow-site/
baseurl:

# Site settings
title: Follow
email: hello@thefollow.inc
description: "Social Trading Ecosystem"


# Team names, titles and social links
people:
- name: Anton
  pic: 1
  position: Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nsspace/
    - title: github
      url: https://github.com/BaldyAsh
    - title: twitter
      url: https://twitter.com/NS_Space
  description: Crypto enthusiast and blockchain developer. 2+ years of software development for scientific purposes (spacecraft), 1 year in DApps development from scratch.<br />Worked on mobile blockchain and fintech open source projects.<br />Specialist in Rocket engineering, Bauman Moscow State Technical University


- name: Petr
  pic: 2
  position: Advisor
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/korolevpetr/
    - title: github
      url: https://github.com/skywinder
    - title: twitter
      url: https://twitter.com/skywinder
  description: 10+ years experience in enterprise development and architecture for fintech solutions (banking systems, stock exchanges)<br />Worked on information security and protection of personal data.<br />Author and active participant of open source projects<br />MSc in Solid-State Physics,<br />Moscow State University

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/FollowInc
  - title: linkedin
    url: https://www.linkedin.com/company/followinc/
  - title: twitter
    url: https://twitter.com/FollowInc
  - title: facebook
    url: https://www.facebook.com/FollowInc
  - title: medium
    url: https://medium.com/@FollowInc

# Postal address (add as many lines as necessary)
address:
  - line: Around the world
  - line: No kidding

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-time-machine